spring:
  application:
    name: promotion-client-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/devops
#    username: root
#    password: adminadmin
#    name: devops

server:
  port: 8093
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.1:8081/eureka
  instance:
    hostname: 172.17.0.1
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health