spring:
  application:
    name: promotion

#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/devops
#    username: root
#    password: adminadmin
#    name: devops

server:
  port: 8087
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.1:8081/eureka
  instance:
    ip-address: 172.17.0.1
    prefer-ip-address: true
  main:
    allow-bean-definition-overriding: true